### ISSUE TITLE
lastdb invalid argument

### ISSUE THREAD

**Issue by alnf** [Gabaldonlab/redundans#17]
In Ubuntu 14.04 Trusty the correct command is:
`lastdb -v`

While the script uses `--`:

```
aln@notik:~/Science/schools/ngschool2016/ngschool2016-materials/src/redundans$ python redundans.py -v -i test/*.fq.gz -f test/contigs.fa -o test/run1 --sspacebin $SSPACEBIN
Options: Namespace(fasta='test/contigs.fa', fastq=['test/5000_1.fq.gz', 'test/5000_2.fq.gz', 'test/600_1.fq.gz', 'test/600_2.fq.gz'], identity=0.51, iters=2, joins=5, limit=0.2, linkratio=0.7, log=<open file '<stderr>', mode 'w' at 0x7f72fd1cc1e0>, mapq=10, minLength=200, nocleaning=True, nogapclosing=True, noreduction=True, noscaffolding=True, outdir='test/run1', overlap=0.66, resume=False, sspacebin='/home/aln/Science/schools/ngschool2016/ngschool2016-materials/src/SSPACE/SSPACE_Standard_v3.0.pl', threads=4, verbose=True)
[WARNING] Problem checking lastdb version: lastdb: invalid option -- '-'
lastdb: bad option
Traceback (most recent call last):
  File "redundans.py", line 450, in <module>
    main()
  File "redundans.py", line 438, in main
    _check_dependencies(dependencies)
  File "redundans.py", line 370, in _check_dependencies
    if int(curver)<version:
ValueError: invalid literal for int() with base 10: 'option'
```

**Comment by lpryszcz** [comment]
In my Trusty it works. check if you have LASTal version 700+

**Comment by alnf** [comment]
Thanks, it helped.
