### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mictadlo** [Gabaldonlab/redundans#2]
Hi,
I ran redundans inside your docker container, but it failed with `IndexError: list index out of range`

```
$ sudo docker run -v `pwd`:/test -it lpryszcz/redundans /bin/bash
# /root/src/redundans/redundans.py -t 30 -v -i /test/*.fastq -f /test/genome.ctg.fasta
Options: Namespace(fasta='/test/genome.ctg.fasta', fastq=['/test/R1-rmdup-rmconta.fastq', '/test/R2-rmdup-rmconta.fastq'], identity=0.51, iters=2, joins=5, limit=0.2, linkratio=0.7, log=<open file '<stderr>', mode 'w' at 0x7f7a9f57f1e0>, mapq=10, minLength=200, nocleaning=True, nogapclosing=True, noreduction=True, noscaffolding=True, outdir='redundans', overlap=0.66, sspacebin='~/src/SSPACE/SSPACE_Standard_v3.0.pl', threads=30, verbose=True)
Traceback (most recent call last):
  File "/root/src/redundans/redundans.py", line 403, in <module>
    main()
  File "/root/src/redundans/redundans.py", line 398, in main
    o.verbose, o.log)
  File "/root/src/redundans/redundans.py", line 247, in redundant
    limit     = get_read_limit(contigsFname, readLimit, verbose, log)
  File "/root/src/redundans/redundans.py", line 99, in get_read_limit
    stats = fasta_stats(open(fasta))
  File "/root/src/redundans/fasta_stats.py", line 18, in fasta_stats
    faidx = FastaIndex(handle)
  File "/root/src/redundans/FastaIndex.py", line 31, in __init__
    self._generate_index()
  File "/root/src/redundans/FastaIndex.py", line 49, in _generate_index
    stats = self.get_stats(header, seq, offset)
  File "/root/src/redundans/FastaIndex.py", line 144, in get_stats
    linebases, linebytes = len(seq[0].strip()), len(seq[0])
IndexError: list index out of range
```

What could go wrong?

Thank you in advance.

Mic

**Comment by lpryszcz** [comment]
Hi, can you try running it now? 
This was a bug, solved in github, but now pushed to docker image until now... 
Thanks!

**Comment by mictadlo** [comment]
Thank you. The assembly had some problems and I deleted it. The new one with Masurca and with SOAPdenovo works fine. I will stop it and try the new docker container.
