### ISSUE TITLE
fasta2homozygous fails for --identity 0.33 --overlap 0.51

### ISSUE THREAD

**Issue by lpryszcz** [Gabaldonlab/redundans#20]
`~/src/redundans/fasta2homozygous.py -i redundans/MAGSPI*/contigs.fa --identity 0.33 --overlap 0.33`

> Homozygous assembly/ies will be written with input name + '.homozygous.fa.gz'
> # file name      genome size     contigs heterozygous size       [%]     heterozygous contigs    [%]     identity [%]    possible joins  homozygous size  [%]     homozygous contigs      [%]
> 
>  [ERROR] `seq21018_len7789_cov189` (('seq1_len104_cov121', 104, 0, 70, 'seq9735_len101_cov148', 101, 31, 101, '+', 0.8285714285714286, 0.693069306930693, 46)) not in contigs!
>  [ERROR] `seq26477_len7324_cov148` (('seq1_len104_cov121', 104, 0, 81, 'seq9735_len101_cov148', 101, 20, 101, '+', 0.7777777777777778, 0.801980198019802, 45)) not in contigs!
>  [ERROR] `seq20577_len9015_cov141` (('seq3_len238_cov168', 238, 0, 238, 'seq10_len238_cov189', 238, 0, 238, '+', 0.9831932773109243, 1.0, 230)) not in contigs!
>  [ERROR] `seq19649_len8979_cov175` (('seq3_len238_cov168', 238, 0, 84, 'seq16825_len172_cov141', 172, 88, 172, '+', 1.0, 0.4883720930232558, 84)) not in contigs!
>  [ERROR] `seq20482_len6873_cov155` (('seq8_len6349_cov128', 6349, 588, 743, 'seq27924_len149_cov114', 149, 0, 149, '+', 0.8456375838926175, 1.0, 103)) not in contigs!
>  [ERROR] `seq20999_len4731_cov189` (('seq8_len6349_cov128', 6349, 5653, 5935, 'seq5386_len269_cov141', 269, 0, 269, '+', 0.6505576208178439, 1.0, 81)) not in contigs!
>  [ERROR] `seq24053_len5120_cov168` (('seq8_len6349_cov128', 6349, 4540, 4646, 'seq27404_len104_cov189', 104, 0, 104, '+', 0.8653846153846154, 1.0, 77)) not in contigs!
>  [ERROR] `seq24131_len10134_cov155` (('seq8_len6349_cov128', 6349, 6249, 6349, 'seq7853_len154_cov296', 154, 0, 100, '+', 0.84, 0.6493506493506493, 68)) not in contigs!
>  [ERROR] `seq25312_len13069_cov148` (('seq8_len6349_cov128', 6349, 419, 679, 'seq5386_len269_cov141', 269, 0, 269, '+', 0.620817843866171, 1.0, 65)) not in contigs!
>  [ERROR] `seq18534_len7476_cov148` (('seq8_len6349_cov128', 6349, 5849, 5999, 'seq27924_len149_cov114', 149, 0, 149, '+', 0.6912751677852349, 1.0, 57)) not in contigs!
>  [ERROR] `seq24935_len5793_cov162` (('seq8_len6349_cov128', 6349, 493, 613, 'seq14809_len119_cov94', 119, 0, 119, '+', 0.6890756302521008, 1.0, 45)) not in contigs!
> Traceback (most recent call last):
>   File "/home/lpryszcz/src/redundans/fasta2homozygous.py", line 234, in <module>
>     main()
>   File "/home/lpryszcz/src/redundans/fasta2homozygous.py", line 228, in main
>     libraries, limit, o.threads, o.joinOverlap, o.endTrimming, o.verbose)
>   File "/home/lpryszcz/src/redundans/fasta2homozygous.py", line 122, in fasta2homozygous
>     contig2skip, identity = hits2skip(hits, faidx, verbose)
>   File "/home/lpryszcz/src/redundans/fasta2homozygous.py", line 74, in hits2skip
>     if contig2skip[q]:
> KeyError: 'seq18807_len4442_cov148'

**Comment by lpryszcz** [comment]
This is most likely due to corrupted .fai file, try rerunning after: `rm redundans/MAGSPI*/contigs.fa.*`

**Comment by lpryszcz** [comment]
`FastaIndex.py` now should recognise and repair corrupted `.fai`.
