### ISSUE TITLE
Error during execution of redundans

### ISSUE THREAD

**Issue by evolgenomology** [Gabaldonlab/redundans#21]
Hi!

I have successfully used redundans on one of my genome assemblies, but doing it on another one I get this error. Any help with this would be highly appreciated.

Philipp

```

Traceback (most recent call last):
  File "/home/philipp/src/redundans/redundans.py", line 450, in <module>
    main()
  File "/home/philipp/src/redundans/redundans.py", line 445, in main
    o.verbose, o.log)
  File "/home/philipp/src/redundans/redundans.py", line 311, in redundans
    identity, overlap, minLength, resume)
  File "/home/philipp/src/redundans/redundans.py", line 150, in run_scaffolding
    threads, limit, iters=1, resume=resume, verbose=0, log=log, basename=basename)
  File "/home/philipp/src/redundans/redundans.py", line 242, in run_gapclosing
    fasta_stats(index)
  File "/home/philipp/src/redundans/fasta_stats.py", line 26, in fasta_stats
    A, C, G, T = map(sum, zip(*[stats[-4:] for stats in id2stats.itervalues()]))
ValueError: need more than 0 values to unpack
```

**Comment by lpryszcz** [comment]
Can you send me the command line you used and list the output directory `ls -lah redundans_out`?

**Comment by evolgenomology** [comment]
Here you go:
[run1-j3-i3.2log.txt](https://github.com/lpryszcz/redundans/files/568721/run1-j3-i3.2log.txt)

`~/src/redundans/redundans.py -v -i ~/src/redundans/redundans.py -v -i /GenomeData_telfordNAS/Ananus/Ananus-Philipp/trimmed_reads/*2kbp*_paired.fq.gz -f /GenomeData_telfordNAS/Ananus/Ananus-Philipp/lane_300bp_600bp_N300_N600_corrected.dipSPAdes/spades/lane_300bp_600bp_N300_N600_corrected.scaffolds.fasta -o /work/Ananus/redundans/run1-j3-i3 -j 3 --iters 3 2>>redundans/run1-j3-i3.2log`

```
total 3.4G


drwxrwxr-x 3 philipp philipp 4.0K Oct  9 19:35 .
drwxrwxr-x 9 philipp philipp 4.0K Oct 26 10:15 ..
drwxrwxr-x 6 philipp philipp 4.0K Oct  9 19:27 _sspace.1.1
lrwxrwxrwx 1 philipp philipp  151 Oct  9 16:52 contigs.fa -> /GenomeData_telfordNAS/Ananus/Ananus-Philipp/lane_300bp_600bp_N300_N600_corrected.dipSPAdes/spades/lane_300bp_600bp_N300_N600_corrected.scaffolds.fasta
-rw-rw-r-- 1 philipp philipp  20K Oct  9 16:56 contigs.fa.amb
-rw-rw-r-- 1 philipp philipp 5.1M Oct  9 16:56 contigs.fa.ann
-rw-rw-r-- 1 philipp philipp 184M Oct  9 17:01 contigs.fa.bck
-rw-rw-r-- 1 philipp philipp 268M Oct  9 16:56 contigs.fa.bwt
-rw-rw-r-- 1 philipp philipp 2.9M Oct  9 16:58 contigs.fa.des
-rw-rw-r-- 1 philipp philipp 6.4M Oct  9 16:53 contigs.fa.fai
-rw-rw-r-- 1 philipp philipp  67M Oct  9 16:56 contigs.fa.pac
-rw-rw-r-- 1 philipp philipp  461 Oct  9 17:01 contigs.fa.prj
-rw-rw-r-- 1 philipp philipp 134M Oct  9 16:57 contigs.fa.sa
-rw-rw-r-- 1 philipp philipp 346K Oct  9 16:58 contigs.fa.sds
-rw-rw-r-- 1 philipp philipp 346K Oct  9 16:58 contigs.fa.ssp
-rw-rw-r-- 1 philipp philipp 1.1G Oct  9 17:01 contigs.fa.suf
-rw-rw-r-- 1 philipp philipp 268M Oct  9 16:58 contigs.fa.tis
-rw-rw-r-- 1 philipp philipp 259M Oct  9 17:48 contigs.reduced.fa
-rw-rw-r-- 1 philipp philipp  20K Oct  9 17:51 contigs.reduced.fa.amb
-rw-rw-r-- 1 philipp philipp 4.2M Oct  9 17:51 contigs.reduced.fa.ann
-rw-rw-r-- 1 philipp philipp 257M Oct  9 17:51 contigs.reduced.fa.bwt
-rw-rw-r-- 1 philipp philipp 5.3M Oct  9 17:48 contigs.reduced.fa.fai
-rw-rw-r-- 1 philipp philipp  65M Oct  9 17:51 contigs.reduced.fa.pac
-rw-rw-r-- 1 philipp philipp 129M Oct  9 17:52 contigs.reduced.fa.sa
-rw-rw-r-- 1 philipp philipp    0 Oct  9 19:31 _reads.lane_5_2kbp_forward_paired.fq
-rw-rw-r-- 1 philipp philipp    0 Oct  9 19:31 _reads.lane_5_2kbp_reverse_paired.fq
-rw-rw-r-- 1 philipp philipp    0 Oct  9 19:33 _reads.lane_6_2kbp_forward_paired.fq
-rw-rw-r-- 1 philipp philipp    0 Oct  9 19:33 _reads.lane_6_2kbp_reverse_paired.fq
lrwxrwxrwx 1 philipp philipp   45 Oct  9 19:30 _sspace.1.1.fa -> _sspace.1.1/_sspace.1.1.final.scaffolds.fasta
-rw-rw-r-- 1 philipp philipp 1.4M Oct  9 19:31 _sspace.1.1.fa.fai
-rw-rw-r-- 1 philipp philipp    0 Oct  9 19:35 _sspace.1.1._gapcloser.1.1.fa
-rw-rw-r-- 1 philipp philipp    0 Oct  9 19:35 _sspace.1.1._gapcloser.1.1.fa.fai
-rw-rw-r-- 1 philipp philipp 1.1K Oct  9 19:35 _sspace.1.1._gapcloser.1.1.fa.log
-rw-rw-r-- 1 philipp philipp  474 Oct  9 19:35 _sspace.1.1._gapcloser.1.conf
-rw-rw-r-- 1 philipp philipp 374M Oct  9 18:35 _sspace.1.1.lib1.tab
-rw-rw-r-- 1 philipp philipp  95K Oct  9 18:35 _sspace.1.1.lib1.tab.log
-rw-rw-r-- 1 philipp philipp 388M Oct  9 19:22 _sspace.1.1.lib2.tab
-rw-rw-r-- 1 philipp philipp  98K Oct  9 19:22 _sspace.1.1.lib2.tab.log
-rw-rw-r-- 1 philipp philipp  106 Oct  9 19:22 _sspace.1.1.libs.txt
-rw-rw-r-- 1 philipp philipp 282K Oct  9 19:30 _sspace.1.1.sspace.log
```

**Comment by lpryszcz** [comment]
_sspace.1.1._gapcloser.1.1.fa is empty, most likely GapCloser failed. This is most due to empty .fq files as all your reads were removed due to quality filtering. This is properly handled in newer version I'm preparing. In meantime you can run redundans with `--nogapclosing` flag. 

Or you can try newer version, but it's still experimental. 

```
git clone -b make --recursive https://github.com/lpryszcz/redundans.git
cd redundans
(cd bin/bwa && make clean && make)
(cd bin/last && make clean && make)
```

**Comment by evolgenomology** [comment]
Thanks. I'll actually got a new scaffolding by excluding the buggy mate pair reads (only 75% were flagged as correct, so 25% paired end contamination). So I'll try the new version and compare to my current scaffolding.
