### ISSUE TITLE
Issue in Scaffolding

### ISSUE THREAD

**Issue by Bourney** [Gabaldonlab/redundans#28]
Hi, 

When running redundans on the test dataset it passes reduction and library parameters fine, but then returns an error during scaffold construction:
<pre class="source">
Traceback (most recent call last):
  File "./redundans.py", line 512, in <module>
    main()
  File "./redundans.py", line 507, in main
    o.norearrangements, o.verbose, o.log)
  File "./redundans.py", line 314, in redundans
    identity, overlap, minLength, resume)
  File "./redundans.py", line 121, in run_scaffolding
    sspacebin, verbose=0, log=log)
  File "/home/sb36g09/software/redundans/bin/fastq2sspace.py", line 191, in fastq2sspace
    tabFnames = get_tab_files(out, fasta, libnames, libFs, libRs, libIS, libISStDev, libreadlen, cores, mapq, upto, verbose, log)
  File "/home/sb36g09/software/redundans/bin/fastq2sspace.py", line 144, in get_tab_files
    proc = _get_aligner_proc(f1.name, f2.name, ref, cores, verbose, bwalog)
  File "/home/sb36g09/software/redundans/bin/fastq2sspace.py", line 117, in _get_snap_proc
    proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=log)
  File "/local/software/python/2.7.5/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/local/software/python/2.7.5/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
</pre>

Command line was just the one for running the test data:
<pre class="source">
./redundans.py -v -i test/*.fq.gz -f test/contigs.fa -o test/run1
</pre>

Cheers, 
Steve

**Comment by lpryszcz** [comment]
Make sure all components are installed correctly. It's most likely `snap-aligner` problem. Try: 
```
~/src/redundans/bin/snap/snap-aligner
~/src/redundans/bin/bwa/bwa
```

Most likely you'll see and error in one of them. To solve, try installation following README.md
```
git clone --recursive https://github.com/lpryszcz/redundans.git
cd redundans
(cd bin/bwa && make clean && make)
(cd bin/last && make clean && make)
(cd bin/snap && make clean && make)
```

**Comment by lpryszcz** [comment]
got it, the issue occured because you have installed Redundans through [UNIX installer](/lpryszcz/redundans#unix-installer) and SNAP compilation wasn't added to installation procedure. It should be solved with the latest version.
