### ISSUE TITLE
TypeError: 'generator' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by mictadlo** [Gabaldonlab/redundans#31]
Hi, 
I ran:
```
$ python fasta2homozygous.py -i /scratch/fruit-data/BAFB.contigs.fasta -t 25
Homozygous assembly/ies will be written with input name + '.homozygous.fa.gz'
#file name      genome size     contigs heterozygous size       [%]     heterozygous contigs    [%]     identity [%]    possible joins  homozygous size [%]     homozygous contigs      [%]
Traceback (most recent call last):
  File "fasta2homozygous.py", line 239, in <module>
    main()
  File "fasta2homozygous.py", line 233, in main
    o.threads, o.verbose)
  File "fasta2homozygous.py", line 151, in fasta2homozygous
    contig2skip = fasta2skip(out, fasta, faidx, threads, identity, overlap, verbose)
  File "fasta2homozygous.py", line 71, in fasta2skip
    sys.stderr.write(' [ERROR] `%s` (%s) not in contigs!\n'%(q, str(hits[i-1])))
TypeError: 'generator' object has no attribute '__getitem__'
ubuntu@waterhouse-1:/mnt/apps/redundans/bin$ lastal: write error
```

Any idea what did I do wrong?

Thank you in advance.

Michal

**Comment by lpryszcz** [comment]
don't use fasta2homozyous.py directly, rather execute `redundans.py --noscaffolding --nogapclosing`
Note, redundans can scaffold also long reads `-l`
