### ISSUE TITLE
Docker - OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mictadlo** [Gabaldonlab/redundans#32]
Hi,
I used your latest docker container but for some reasons I got `OSError: [Errno 2] No such file or directory`

```
$ docker run -v `pwd`:/test:rw -it lpryszcz/redundans

root@7bf273fe0c52:/# head /test/BAFB.contigs.fasta
>tig00000003 len=68902 reads=220 covStat=35.22 gappedBases=no class=contig suggestRepeat=no suggestCircular=no
AAAAGTTTTCAGAGAAGTAAGCTTCTGTGGTTTTATCATGGATAGTGCAGTTATGTCCAGCGACAATAGATCTCTATCTTATTGAAGGAATTTTGTGTTA
TTCACACTCTTGTTTTTGGCCTTCAGGAAGACTGATCGAGTCATCTTCAGCTAGAGTGGTAATTCTTCTGTCTGTGGCATCTAGCCATTCTTCCAACCTG
TTTTCTTTTCTTCTTCTTTTTCTTGTTACATTACACTGTAGTTGATGCGTCGATAAGAAGCTAAGATTTTATTTGCTGTCATTGCTTAATGTCTTTGTCA
TGTTCAAACTGACTGTAAGAAAATACTTTGTTGGAAATTCATGCTTCTATGCTTCAAGTCACACCTTATATAGATTCTGATCAAAAGCTTTAAAGGTAAA
AGATGATATAAGGCTTATAGAACGACTCTGATAGTTTCTGGGAGCAATACTGTACCAAGACATCTTATTACTTGCCAACAGTTTAATCCATTCATATATT
CAGCTAGTGCATTGCTATGGTCTGGTAAATTTTCTTTTTCTTTTGAGTAAACAGTTTTGTCTAAAGGCTCTTCTGTTTTTTATTGTAATGTCAGATGCTA
AGTTGAGAAATAACACTAAATTTATGCTGCATCAATTCTAACTCATTCTAGCTTGCTGCCTGTTATCTTATATCAAAAGGCTGATATGGAGGAGACGGAG
AGAGACTTGAAAAAGAACTACGAGAGTATGGGTATTTCATAGACATGCATATTTCAGTGTGATATAGTCAGGTAAATGCATATTGCAAGTGGACTTGAAC
GACAATTTTAAGAATATTAAATTATGTCTTGCAAATGAACATATTCTAAAGTATCAAAAATCAAAGTTGTCAAGCTAAAGAGAAAGAAACTAAAGGTTCT

root@7bf273fe0c52:/# /root/src/redundans/bin/fasta2homozygous.py -i /test/BAFB.contigs.fasta -t 25
Homozygous assembly/ies will be written with input name + '.homozygous.fa.gz'
#file name      genome size     contigs heterozygous size       [%]     heterozygous contigs    [%]     identity [%]    possible joins  homozygous size [%]     homozygous contigs      [%]
Traceback (most recent call last):
  File "/root/src/redundans/bin/fasta2homozygous.py", line 238, in <module>
    main()
  File "/root/src/redundans/bin/fasta2homozygous.py", line 232, in main
    o.threads, o.verbose)
  File "/root/src/redundans/bin/fasta2homozygous.py", line 150, in fasta2homozygous
    contig2skip = fasta2skip(out, fasta, faidx, threads, identity, overlap, verbose)
  File "/root/src/redundans/bin/fasta2homozygous.py", line 63, in fasta2skip
    for i, (score, t, q, algLen, identity, overlap) in enumerate(hits, 1):
  File "/root/src/redundans/bin/fasta2homozygous.py", line 36, in fasta2hits
    last = run_last(fasta.name, identityTh, threads, verbose)
  File "/root/src/redundans/bin/fasta2homozygous.py", line 30, in run_last
    proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=sys.stderr)        
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

What did I miss?

Thank you in advance.

Michal

**Comment by lpryszcz** [comment]
[issues/31](31)
