### ISSUE TITLE
FastaIndex.py and fasta_stats.py missing?

### ISSUE THREAD

**Issue by pwkooij** [Gabaldonlab/redundans#34]
I just installed redundans both through the git repository as well as with the UNIX installer, but both versions give me the following error when I try to run the test:

`~/redundans$ ./redundans.py -v -i test/*.fq.gz -f test/contigs.fa -o test/run1
Traceback (most recent call last):
  File "./redundans.py", line 34, in <module>
    from fasta2homozygous import fasta2homozygous
  File "/home/pepijn/redundans/bin/fasta2homozygous.py", line 17, in <module>
    from FastaIndex import FastaIndex`

When I look at the bin folder it seems that the symlinks for both python scripts are present, but they seem empty. Any idea what the problem might be?

**Comment by lpryszcz** [comment]
It seems submodule dependency broke after working with pyScaf. It should be solved now. 
Can you fetch fresh repo and let me know? 

```
git clone --recursive https://github.com/lpryszcz/redundans.git
cd redundans && bin/.compile.sh
```

**Comment by pwkooij** [comment]
Looks like that did the trick!

```
`Options: Namespace(fasta='test/contigs.fa', fastq=['test/5000_1.fq.gz', 'test/5000_2.fq.gz', 'test/600_1.fq.gz', 'test/600_2.fq.gz', 'test/pacbio.fq.gz'], identity=0.51, iters=2, joins=5, limit=0.2, linkratio=0.7, log=<open file '<stderr>', mode 'w' at 0x7fbafe9c21e0>, longreads=[], mapq=10, minLength=200, nocleaning=True, nogapclosing=True, norearrangements=False, noreduction=True, noscaffolding=True, outdir='test/run1', overlap=0.8, reference='', resume=False, threads=4, verbose=True)

##################################################
[Wed May 24 16:27:53 2017] Reduction...
#file name	genome size	contigs	heterozygous size	[%]	heterozygous contigs	[%]	identity [%]	possible joins	homozygous size	[%]	homozygous contigs	[%]
test/run1/contigs.fa	163897	245	66377	40.50	221	90.20	94.854	0	97520	59.50	24	9.80

##################################################
[Wed May 24 16:27:57 2017] Estimating parameters of libraries...
 Aligning 19504 mates per library...
Insert size statistics				Mates orientation stats
FastQ files	read length	median	mean	stdev	FF	FR	RF	RR
test/5000_1.fq.gz test/5000_2.fq.gz	50	4986	4981.70	692.22	0	4067	14	0
test/600_1.fq.gz test/600_2.fq.gz	100	599	599.36	47.13	0	10000	0	0

##################################################
[Wed May 24 16:27:58 2017] Scaffolding...
 iteration 1.1: test/run1/contigs.reduced.fa	24	97520	39.355	17	94157	7321	2195	0	29603
   19505 pairs. 17288 passed filtering [88.63%]. 1653 in different contigs [8.47%].
    1529 pairs. 572 in different contigs [37.41%].
 iteration 1.2: test/run1/_sspace.1.1.fa	3	97822	39.343	3	97822	87592	6203	962	87592
   19505 pairs. 17582 passed filtering [90.14%]. 197 in different contigs [1.01%].
    1079 pairs. 137 in different contigs [12.70%].
 iteration 2.1: test/run1/_sspace.1.2.fa	2	97951	39.343	2	97951	87592	10359	1091	87592
   19505 pairs. 15142 passed filtering [77.63%]. 679 in different contigs [3.48%].
    3398 pairs. 177 in different contigs [5.21%].
 iteration 2.2: test/run1/_sspace.2.1.fa	1	99283	39.343	1	99283	99283	99283	2423	99283
   19505 pairs. 15149 passed filtering [77.67%]. 0 in different contigs [0.00%].
    3391 pairs. 0 in different contigs [0.00%].

##################################################
[Wed May 24 16:28:01 2017] Gap closing...
 iteration 1.1: test/run1/scaffolds.fa	1	99283	39.343	1	99283	99283	99283	2423	99283

##################################################
[Wed May 24 16:28:02 2017] Final reduction...
#file name	genome size	contigs	heterozygous size	[%]	heterozygous contigs	[%]	identity [%]	possible joins	homozygous size	[%]	homozygous contigs	[%]
test/run1/scaffolds.filled.fa	100013	1	0	0.00	0	0.00	0.000	0	100013	100.00	1	100.00

##################################################
[Wed May 24 16:28:02 2017] Reporting statistics...
#fname	contigs	bases	GC [%]	contigs >1kb	bases in contigs >1kb	N50	N90	Ns	longest
test/contigs.fa	245	163897	40.298	24	117391	3975	233	0	29603
test/run1/contigs.fa	245	163897	40.298	24	117391	3975	233	0	29603
test/run1/contigs.reduced.fa	24	97520	39.355	17	94157	7321	2195	0	29603
test/run1/_sspace.1.1.fa	3	97822	39.343	3	97822	87592	6203	962	87592
test/run1/_sspace.1.2.fa	2	97951	39.343	2	97951	87592	10359	1091	87592
test/run1/_sspace.2.1.fa	1	99283	39.343	1	99283	99283	99283	2423	99283
test/run1/_sspace.2.2.fa	1	99283	39.343	1	99283	99283	99283	2423	99283
test/run1/scaffolds.fa	1	99283	39.343	1	99283	99283	99283	2423	99283
test/run1/_gapcloser.1.1.fa	1	100013	39.721	1	100013	100013	100013	2	100013
test/run1/scaffolds.filled.fa	1	100013	39.721	1	100013	100013	100013	2	100013
test/run1/scaffolds.reduced.fa	1	100013	39.721	1	100013	100013	100013	2	100013

##################################################
[Wed May 24 16:28:02 2017] Cleaning-up...
#Time elapsed: 0:00:09.440504`
```
