### ISSUE TITLE
Redundans error- OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Deeptirao** [Gabaldonlab/redundans#42]
![redundans_command](https://user-images.githubusercontent.com/34051431/33302978-01b2e4a6-d426-11e7-90ed-e8bb8a6d985b.png)

Please check the above screen shot and help me in resolving the error.

**Comment by lpryszcz** [comment]
It seems your genome (390Mb) is already assembled into 14 chromosomes. Why do you want to use Redundans on it?

**Comment by Deeptirao** [comment]
![redundans_error2](https://user-images.githubusercontent.com/34051431/33699613-33620d22-db3a-11e7-824b-60f41510aee7.png)

Yes, I made a mistake in the command earlier. My intention was to use the 390 MB genome as a reference. I did run it again with corrections, but the same error appeared even when I did that. Please check the screen shot.

**Comment by lpryszcz** [comment]
make sure `snap-aligner` is correctly installed and works (`REDUNDANSPATH/bin/snap/snap-aligner`)

**Comment by lpryszcz** [comment]
alternatively use **-b** to use BWA instead of snap-aligner

**Comment by SvitlanaLukicheva** [comment]
Hello, I have the same issue. Installation of `snap-aligner` and/or usage of **-b** option didn't solve the problem.

```Options: Namespace(fasta='/CECI/proj/pmg/gonioctena_quinquepunctata/assemblies/wtdbg/gq.ctg.4th.fa', fastq=['/CECI/proj/pmg/gonioctena_quinquepunctata/input/illumina/gq__illumina_250-500__R1.fastq', '/CECI/proj/pmg/gonioctena_quinquepunctata/input/illumina/gq__illumina_250-500__R2.fastq'], identity=0.51, iters=2, joins=5, limit=0.2, linkratio=0.7, log=<open file '<stderr>', mode 'w' at 0x7fea0fa30270>, longreads=['/CECI/proj/pmg/gonioctena_quinquepunctata/input/nanopore/gq_nanopore.fastq'], mapq=10, mem=16, minLength=200, nocleaning=True, nogapclosing=True, norearrangements=False, noreduction=True, noscaffolding=True, outdir='/globalfs/ulb/ebe/slukiche/redundans__gq__wtdbg', overlap=0.8, reference='', resume=False, threads=16, tmp='/tmp', usebwa=True, verbose=True)
Traceback (most recent call last):
  File "/CECI/home/ulb/ebe/slukiche/assemblers/redundans/redundans/redundans.py", line 539, in <module>
    main()
  File "/CECI/home/ulb/ebe/slukiche/assemblers/redundans/redundans/redundans.py", line 527, in main
    _check_dependencies(dependencies)
  File "/CECI/home/ulb/ebe/slukiche/assemblers/redundans/redundans/redundans.py", line 441, in _check_dependencies
    p = subprocess.Popen([cmd, '--version'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/local/python/2.7.3/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/local/python/2.7.3/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory```
