### ISSUE TITLE
Error during test

### ISSUE THREAD

**Issue by chaijinchao** [Gabaldonlab/redundans#7]
HI,
         **I run the example as：
                       ./redundans.py -v -i test/*.fq.gz -f test/contigs.fa -o test/run1
         but  I get this error：**
                       
Traceback (most recent call last):
  File "/share/work1/staff/chaijc/software/redundans/redundans.py", line 517, in <module>
    main()
  File "/share/work1/staff/chaijc/software/redundans/redundans.py", line 512, in main
    o.norearrangements, o.verbose, o.log)
  File "/share/work1/staff/chaijc/software/redundans/redundans.py", line 312, in redundans
    libraries = get_libraries(fastq, lastOutFn, mapq, threads, verbose, log)
  File "/share/work1/staff/chaijc/software/redundans/redundans.py", line 59, in get_libraries
    genomeFrac, stdfracTh, maxcfracTh)
  File "/share/work1/staff/chaijc/software/redundans/bin/fastq2insert_size.py", line 189, in fastq2insert_size
    isstats = get_isize_stats(fq1, fq2, fasta, mapq, threads, limit, verbose, stdfracTh, maxcfracTh)
  File "/share/work1/staff/chaijc/software/redundans/bin/fastq2insert_size.py", line 111, in get_isize_stats
    aligner = _get_snap_proc(fq1, fq2, fasta, threads, verbose, alignerlog)            
  File "/share/work1/staff/chaijc/software/redundans/bin/fastq2sspace.py", line 133, in _get_snap_proc
    proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=log)
  File "/share/software/software/python-2.7_install_dir/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/share/software/software/python-2.7_install_dir/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**how can i solve it， thanks for giving me some suggestions.**

**Comment by lpryszcz** [comment]
make sure [SNAP](https://github.com/amplab/snap) is correctly built.

**Comment by jwasmuth** [comment]
@chaijinchao I got the same error. The solution is 
`cd bin/snap && make clean && make && cd ../..`

**Comment by lpryszcz** [comment]
Thanks @jwasmuth 
hmm, it seems sometimes compilation of SNAP fails (ie in my laptop). In such cases installing it from [bioconda](https://bioconda.github.io/) seems the easiest solutions `conda install snap-aligner`
