### ISSUE TITLE
OSError: [Errno 17] File exists

### ISSUE THREAD

**Issue by Kata-Pa** [Gabaldonlab/redundans#75]
Hello!

I ve been running Redundans in the past several times with no problem (with the only difference of using --noscaffolding), but suddenly now I get an error (even if I add noscaffolding parameter). Here is my command:
redundans.py -f ../flye/assembly.fasta  -i ../../My_Illumina/Trimmed/Cylindro.Illumina.fwd.Gold.5.20.paired.fastq ../../My_Illumina/Trimmed/Cylindro.Illumina.rv.Gold.5.20.paired.fastq ../../My_Illumina/Trimmed/Cylindro.IlluminaRun2.fwd.Gold.5.20.paired.fastq ../../My_Illumina/Trimmed/Cylindro.IlluminaRun2.rv.Gold.5.20.paired.fastq -l ../All_Minion.fastq --log MaSuRCa_Redund -o MaSuRCa_Redund

And the error I get is: 
Traceback (most recent call last):
  File "/home/katerina87/Tools/redundans/redundans.py", line 541, in <module>
    main()
  File "/home/katerina87/Tools/redundans/redundans.py", line 536, in main
    o.norearrangements, o.verbose, o.usebwa, o.log, o.tmp)
  File "/home/katerina87/Tools/redundans/redundans.py", line 289, in redundans
    os.makedirs(outdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: 'MaSuRCA_Redund'

Even though the output file does not exist when I run the command. I am using python 2.7 and I tried in two different servers,I got the same error. 
Any hint on what is wrong?

Thank you!
/Katerina

**Comment by Kata-Pa** [comment]
Ok, no need to reply here (though I guess noone was going to), I solved it myself.
Avoid using the same name for log and output, as this creates the file exists error.
