### ISSUE TITLE
OSError: [Errno 20] Not a directory

### ISSUE THREAD

**Issue by Kata-Pa** [Gabaldonlab/redundans#76]
Hello,

I am running redundans as shown below:
python redundans.py -f assembly.fasta -i Cylindro.Illumina.fwd.Gold.5.20.paired.fastq Cylindro.Illumina.rv.Gold.5.20.paired.fastq Cylindro.IlluminaRun2.fwd.Gold.5.20.paired.fastq Cylindro.IlluminaRun2.rv.Gold.5.20.paired.fastq -l All_Minion.fastq --log MaSuRCa_Redundans -o MaSuRCa_Redund -t 8

and I get this error:
Traceback (most recent call last):
  File "../../../Tools/redundans/redundans.py", line 541, in <module>
    main()
  File "../../../Tools/redundans/redundans.py", line 536, in main
    o.norearrangements, o.verbose, o.usebwa, o.log, o.tmp)
  File "../../../Tools/redundans/redundans.py", line 332, in redundans
    identity, overlap, minLength, resume)
  File "../../../Tools/redundans/redundans.py", line 129, in run_scaffolding
    sspacebin, verbose=0, usebwa=usebwa, log=log)
  File "/home/katerina87/Tools/redundans/bin/fastq2sspace.py", line 274, in fastq2sspace
    cores, mapq, upto, verbose, usebwa, log)
  File "/home/katerina87/Tools/redundans/bin/fastq2sspace.py", line 228, in get_tab_files
    proc = _get_aligner_proc(f1.name, f2.name, ref, cores, verbose, bwalog)
  File "/home/katerina87/Tools/redundans/bin/fastq2sspace.py", line 128, in _get_snap_proc
    subprocess.Popen(idxcmd.split(), stdout=log, stderr=log).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 20] Not a directory

I get contigs.reduced.fa and scaffolds.reduced.fa as output but I think the output from the short reads scaffolding is missing. So maybe it's something wrong in my -i parameter?

Thank you in advance,
/Katerina

**Comment by lpryszcz** [comment]
Hi @Kata-Pa , yes, you identified the problem right. 
Redundans expects two FastQ files for each short-read library (`_1.fastq` & `_2.fastq`), while you have combined (shuffled) FastQ. Just split your forward and reverse reads into two separate files for every library. 
Cheers,
